pool:
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main

steps:
  - task: UseDotNet@2
    inputs:
      version: '5.0.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonarcloud'
      organization: 'jenshenrik'
      scannerMode: 'MSBuild'
      projectKey: 'jenshenrik_brewlog-api'
      projectName: 'brewlog-api'